# Generated by Django 3.2.5 on 2022-06-27 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=30)),
                ('affiliation', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=50)),
                ('web_link', models.URLField(max_length=400)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=19)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=2000)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=70)),
                ('qualification', models.CharField(max_length=70)),
                ('employment_type', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('min_exp', models.IntegerField()),
                ('max_exp', models.IntegerField()),
                ('currency', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('app_deadline', models.CharField(max_length=30)),
                ('dead_date', models.DateField()),
                ('description', models.CharField(max_length=4000)),
                ('draft', models.BooleanField(default=False)),
                ('pinned_post', models.BooleanField(default=False)),
                ('featured_post', models.BooleanField(default=True)),
                ('free_post', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.company')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.discipline')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.field')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.industry')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.region')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.role')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=20)),
                ('order_ref', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=30)),
                ('amount_paid', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('comment_content', models.CharField(max_length=1000)),
                ('date_commented', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.post')),
            ],
        ),
    ]
