# Generated by Django 3.2.5 on 2022-06-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_invoice_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credits_received',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
