# Generated by Django 3.2.5 on 2022-06-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_payment_credits_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.BooleanField(),
        ),
    ]
